version: '3.9'

volumes:
  pg_data:

services:
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 5432:5432

  app:
     container_name: app
     build: .
     env_file:
       - .env
     restart: unless-stopped
     ports:
       - 8000:8000
     expose:
       - "8000"
     depends_on:
       - postgres
